apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-applicationset
spec:
  generators:
  - list:
      elements:
      - appName: calc-sample
        namespace: calc-sample
  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      source:
        repoURL: https://github.com/koamano/calc-sample.git
        targetRevision: HEAD
        path: sample/dev
      destination:
        name: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true  
