apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-applicationset
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
        # values:
        #   - appName: sample-application-dev
        #   - namespace: sample
        #   - repoURL: https://github.com/koamano/calc-sample.git
        #   - path: overlays/dev        
  template:
    metadata:
      name: sample-application-dev
    spec:
      project: default
      source:
        repoURL: https://github.com/koamano/calc-sample.git
        targetRevision: HEAD
        path: overlays/dev 
      destination:
        server: '{{url}}'
        namespace: sample
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true  

